### PR TITLE
Update script for latest GCC

### PR DESCRIPTION
**Pull request by netbospl**
Update to latest GCC

### CODE REVIEW

**Comment by ptr1337** [comment]
Maybe change also:
islver=0.23
binutils=2.36

**Comment by netbospl** [comment]
I think MingW build with GCC-11 is related to this issue and will not build until that's fixed for the target i686-w64-mingw32
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99913

**Comment by netbospl** [comment]
Successfully built
gcc-mostlyportable-11.1.1-releases-gcc.11.1.0.r77.g8482ed658ca
and
mingw-mostlyportable-10.3.1-releases-gcc.10.3.0.r146.gd7c8e626153
Tried few more things, but this looks like best I can do and fill not make any further commits.
So bumped tools versions, gcc release 11, mingw release 10 without hsa is where I give up.
Haven't tried fortran, ada or any others optional stuff, good enough for me anyways.

**Comment by Tk-Glitch** [comment]
Let's do that for now :)
Thank you! :frog: :heart:

**Comment by ptr1337** [comment]
Good work, fortan and ada are really paini to get them running.

Maybe if it help i found some patches from gentoo, with them is the normal gcc11 build much more "easier" to build without errors. 
https://github.com/ptr1337/linux-cacule-aur/tree/master/patches/gcc/gcc/11.1.0

There are also for gcc 10.3 some patches. 

Maybe they can help, but good work thanks!

**Pull request merged**
